name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Enable manual dispatch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: rustup update stable
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Generate code coverage
      run: cargo llvm-cov --all-features --remap-path-prefix --html
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './target/llvm-cov/html'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: coverage
    steps:
    - id: deployment
      uses: actions/deploy-pages@v1
